export const HERO_GREETINGS: string[] = [
  "What's on your mind today?",
  "Ready when you are.",
  "How can I help today?",
  "Ask me anything.",
  "What would you like to do?",
  "Let's get started.",
  "What are we working on today?",
  "Tell me what you need.",
  "I'm here to help.",
  "Where would you like to begin?",
  "What can I assist you with?",
  "How can we make progress today?",
  "What would you like to explore?",
  "Share your question or idea.",
  "Let's solve something together.",
  "What's your next challenge?",
  "Let's build something great.",
  "Your AI assistant is ready.",
  "Let's make things happen.",
];